### ISSUE TITLE
Simplify code structure

### ISSUE THREAD

**Issue by CCharlieLi** [SkyroverTech/SkyoverCF#1]
Hi @budebulai 

To help you get familiar with Git and speed up the development. We need your help to simplify the code structure by:
- Remove support of other board and keep Naze32 only
- Remove other flight mode and keep custom mode(please talk to @Innoecho if you have any ques)

**Comment by CCharlieLi** [comment]
Please make sure:
- Make a branch at your localhost
- Modify your code
- Push your branch
  I'll have someone review the code and merge later.

**Comment by budebulai** [comment]
Hi CCharlieLi, I've read your message, and I'll take on this matter

**Comment by CCharlieLi** [comment]
@budebulai If there's any blocker?
