### ISSUE TITLE
Spamming #cleanfight with your Travic CI builds

### ISSUE THREAD

**Issue by add1ct3dd** [SkyroverTech/SkyoverCF#10]
Not sure if you guys are aware, but builds are spamming #cleanflight on freenode.

travis-ci (~travis-ci@ec2-54-145-158-42.compute-1.amazonaws.com) has joined. «144 people»
<travis-ci> SkyroverTech/SkyroverCF#26 (master - e9baef7 : Charlie Li): The build passed.
<travis-ci> Change view : https://github.com/SkyroverTech/SkyroverCF/compare/e06c4180635a...e9baef7aaf56
<travis-ci> Build details : https://travis-ci.org/SkyroverTech/SkyroverCF/builds/92901465
travis-ci (~travis-ci@ec2-54-145-158-42.compute-1.amazonaws.com) has parted. «143 people»

Kind of annoying, when it's not cleanflight. Hoping you guys can fix it :)

**Comment by CCharlieLi** [comment]
Sorry for this truely. Thanks for your reminding and thanks for the Cleanflight ; )
