### ISSUE TITLE
API design and params list

### ISSUE THREAD

**Issue by CCharlieLi** [SkyroverTech/SkyoverCF#5]
@budebulai We need to design a API class to interact with outside connectors, to set params of flight mode easily. But first we need a params list to determine what params are needed in this API.
- Please add the list in [project wiki](https://github.com/SkyroverTech/SkyroverCF/wiki)
- Can I expect it before this Friday?

**Comment by budebulai** [comment]
sorry for delay

**Comment by CCharlieLi** [comment]
Thanks. If you are ready, please pull request.

**Comment by CCharlieLi** [comment]
Done. Thanks.
